backend:
  name: git-gateway
  branch: main  # or master (check your repo branch name)

media_folder: "images"       # Where uploaded images are stored
public_folder: "/images"     # How they're accessed in the site

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
